package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-cpus, returns=[CpuInfo], data=null}</pre>
 * @deprecated The query-cpus command is replaced by the query-cpus-fast command.
 */
// QApiCommandDescriptor{name=query-cpus, returns=[CpuInfo], data=null}
@Deprecated
public class QueryCpusCommand extends QApiCommand<java.lang.Void, QueryCpusCommand.Response> {

	/** Response to a QueryCpusCommand. */
	public static class Response extends QApiResponse<java.util.List<CpuInfo>> {
	}

	/** Constructs a new QueryCpusCommand. */
	public QueryCpusCommand() {
		super("query-cpus", Response.class, null);
	}

}
